server:
  port: 5637


spring:
  application:
    name: nacos-config-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 49.235.140.202:8848


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-config-client


