server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
            discovery:
              server-addr: 49.235.140.202:8848 #配置Nacos地址
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://collect-account-service #匹配后提供服务的路由地址
          predicates:
            - Path=/account/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8200          #匹配后提供服务的路由地址
          uri: lb://collect-account-consumer #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/lb/**         # 断言，路径相匹配的进行路由
            - After=2021-01-28T15:51:37.485+08:00[Asia/Shanghai] #2021-01-28年15:51:37后才能执行
            - Cookie=username,zzyy
            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式


